### ISSUE TITLE
fix: footer design

### ISSUE THREAD

**Issue by codadept** [gdsc-nits-org/guidance-grid#33]
- decrease the spaces between different sections in the footer
- decrease the font of "Google Developer Student Clubs NITS" to fit in one line according to design

Design
![image](https://user-images.githubusercontent.com/63517465/213868341-090dbbd5-ca24-41ae-9274-b734da1cdd31.png)

Current
![image](https://user-images.githubusercontent.com/63517465/213868355-9b74037f-3140-4fe3-8d7e-58c57e292b69.png)

**Comment by byt3h3ad** [comment]
pls check #34
